language: java
install: true

addons:
  sonarcloud:
    organization: "ka5p3rr"
    token:
      secure: $SONAR_CLOUD_KEY

os: linux
dist: trusty
jdk: oraclejdk8

before_script:
    - cd PotassiumOverload
    - chmod +x gradlew

script:
    - ./gradlew clean tests:test
    - ./gradlew sonarqube
